python3 synthetic_data_generator_with_continuous_mark.py \
        --dataset_name stationary_renewal \
        --data_type sequence \
        --seq_length 64 \
        --train_size 160000 \
        --eva_size 20000 \
        --test_size 20000 \
        --random_seed 32 \
        --ndim 2 \
        --num_classes 7 \
